baseURL: "https://www.codeclub.top/"
title: 编程知识分享-CodeClub
defaultContentLanguage: zh
languageCode: zh
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true

hasCJKLanguage: true

outputs:
  home:
  - HTML
  - RSS
  - JSON

taxonomies:
  tag: tags

menu:
  main:
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 10
    - identifier: search
      name: 搜索
      url: /search/
      weight: 20
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 30
    - identifier: RSS
      name: 订阅
      url: /index.xml
      weight: 40
    - identifier: github
      name: GitHub
      url: https://github.com/pengzhezhe
      weight: 50
  
params:
  env: production
  title: CodeClub
  description: ""
  keywords: [Blog, CodeClub, Zhezhe Peng]
  author: Zhezhe Peng
  DateFormat: "2006-01-02"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    favicon: /img/favicon.png
    disableHLJS: true

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    style: monokai