baseURL: "https://www.codeclub.top/"
title: CodeClub
defaultContentLanguage: zh
languageCode: zh
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

hasCJKLanguage: true

outputs:
  home:
  - HTML
  - RSS
  - JSON

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true

taxonomies:
  tag: tags

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: about
      name: About
      url: https://github.com/pengzhezhe
      weight: 40
    - identifier: RSS
      name: RSS
      url: /index.xml
      weight: 50
  
params:
  env: production
  title: CodeClub
  description: ""
  keywords: [Blog, CodeClub, Zhezhe Peng]
  author: Zhezhe Peng
  DateFormat: "2006-01-02"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true
    disableFingerprinting: false

  label:
    text: "CodeClub"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary", "content"]

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
  highlight:
    noClasses: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    anchorLineNos: false
    style: monokai